### ISSUE TITLE
Colour on open brackets is burning my eyes

### ISSUE THREAD

**Issue by ilium007** [ranelpadon/thonny-onedark#1]
Is there any way to change this salmon colour shown below. It happens at an open bracket and in the syntax screen when an incorrect argument is typed in.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/732766/161648811-a71d28f4-d909-49ba-9d11-5d8f9c05859c.png">

**Comment by ilium007** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/732766/161649054-f4cc0057-3516-4efe-a720-40d78d2f9b90.png">

Its the unclosed string colour

**Comment by ranelpadon** [comment]
@ilium007 I agree, it doesn't look good. Will check if it's possible to control that color/context in Thonny. Thanks for your feedback.

**Comment by ranelpadon** [comment]
@ilium007 Currently, we have this combo for such scenario:
- Foreground=WHITE
- Background=RED

These are some of the simple solutions, while not adding a new color: 

**A.** Use Black text instead of White to improve contrast. Seems that the White text is the main reason why your screenshots are not pleasant to look at:
- Foreground=BLACK
- Background=RED
<img width="707" alt="Screen Shot 2022-04-05 at 5 22 18 PM" src="https://user-images.githubusercontent.com/4292088/161724312-8bf8dc08-ceb3-4f19-ace4-d33ba2875316.png">

**B.** Use Red text and use the default Black background:
- Foreground=RED
- Background=BLACK/Default
<img width="708" alt="Screen Shot 2022-04-05 at 5 27 35 PM" src="https://user-images.githubusercontent.com/4292088/161724720-a3ea026c-7884-4762-a459-1457d3502500.png">

Personally, I prefer Option **A**, and it looks acceptable to me. What do you think? Thanks

**Comment by ranelpadon** [comment]
@ilium007 pushed the changes now in version `0.2.0`. The salmon color looks better with the black text. You could take a look by upgrading the Thonny OneDark plugin (`Tools -> Manage plug-ins`) from `0.1.1` to `0.2.0`:

<img width="926" alt="Screen Shot 2022-04-06 at 2 38 27 PM" src="https://user-images.githubusercontent.com/4292088/161911361-d0ccf51e-5ec8-483a-8a1b-99182197067c.png">

Let me know what you think. Thanks

**Comment by ilium007** [comment]
Great!! Thanks for that!
